# Generated by Django 4.2.29 on 2026-09-05 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0068_issue_cached_display_title_a11y_and_more'),
        ('review', '0026_merge_20260603_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerPoolMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='candidate', max_length=20)),
                ('source', models.CharField(choices=[('author', 'Author'), ('manual', 'Manual'), ('previous_reviewer', 'Previous Reviewer'), ('import', 'Import'), ('editorial_board', 'Editorial Board'), ('external', 'External')], default='manual', max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_pool_memberships', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_pool_memberships', to='journal.journal')),
            ],
            options={
                'ordering': ('journal', 'account'),
            },
        ),
        migrations.AddConstraint(
            model_name='reviewerpoolmembership',
            constraint=models.UniqueConstraint(fields=('account', 'journal'), name='unique_reviewer_pool_membership'),
        ),
    ]
